apiVersion: v1
kind: Pod
metadata:
  name: httpd-2
  labels:
    app: httpd
spec:
  containers:
    - image: centos/httpd-24-centos7
      name: httpd-2
      command: [ "/bin/bash" ]
      args: [ "-c", "ln -s /etc/hostname /var/www/html/index.html && /usr/bin/run-httpd" ]
      ports:
        - containerPort: "8080"
          name: http-proto
      volumeMounts:
      ## Use a storage here because the directory /var/www/html 
      ## does not have write permissions
      - mountPath: /var/www/html
        name: htmldir 
  volumes:
    - name: htmldir
      emptyDir: {}

